Adds QuerySourceMapping.Remove API
re-motion/Relinq pull request #8
Opened 2016-09-23 19:49 UTC by anpete

Small change to add a Remove API to QuerySourceMapping.

2016-09-26 06:01 UTC, MichaelKetting commented on Core/Clauses/QuerySourceMapping.cs
> +    public void RemoveMapping (IQuerySource querySource)
Please move it up to ReplaceMapping so we keep the modification-methods grouped together.

2016-09-26 06:15 UTC, MichaelKetting requested changes
Hi Andrew! 

Thanks for the PR. Some minor formatting issues but the code looks good, otherwise :)

It would be great if you could also create a corresponding feature request in our issue tracker (https://www.re-motion.org/jira/projects/RMLNQ/summary) and use the ticket number in the commit message (RMLNQ-xxx ...)

Do you have the Entity Framework feature at hand that needs the remove-logic? I'd like to learn more :)

~Michael

PS: We'll also need the CLA, please, before merging the request.

2016-09-26 06:15 UTC, MichaelKetting commented on Core/Clauses/QuerySourceMapping.cs
> +          string.Format ("Query source ({0}) has not been associated with an expression, cannot remove its mapping.", querySource));
Two more whitespaces here, please: Double-indentation for statement continuation.

2016-09-26 18:43 UTC, anpete commented
Created https://www.re-motion.org/jira/browse/RMLNQ-106

2016-09-26 20:22 UTC, anpete commented
Updated.

As for the use case, it is basically that in our relational base framework we can end up removing an IQuerySource from a QueryModel _after_ a query mapping has been added for it by our core layer.

2016-09-27 15:41 UTC, MichaelKetting commented
Thanks. Looks good :)

Re the use case: Ah, I see. Basically, a consistency guard to make sure nothing gets overlooked. Cool.

2016-09-27 17:16 UTC, anpete commented
Commit message updated. I sent the CLA yesterday.

2016-10-13 06:50 UTC, merged

2016-10-13 06:55 UTC, MichaelKetting commented
@anpete  I'll be doing a 2.2.0-alpha.1 release today or tomorrow but I'll wait with the next full release until there's a downstream stable release that depends on it :)

2016-10-13 17:39 UTC, anpete commented
@MichaelKetting Thanks. Any chance we could get this one in soon? https://www.re-motion.org/jira/browse/RMLNQ-105

2016-10-18 07:20 UTC, MichaelKetting commented
@anpete re rmlnq-105 I've put it on my shortlist and get back to you on this after this weekend. It's a bit of tricky issue, if I'm remembering this correctly.

2016-10-24 15:05 UTC, MichaelKetting commented
@anpete re rmlnq-105: Okay, turned out to be tricky. I've allocated the upcoming Wednesday for it.